name: Frontend CI

on:
  push:
    branches: [ main, developer ]
  pull_request:
    branches: [ main, developer ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test -- --ci --coverage
